### ISSUE TITLE
this.pc.setRemoteDescription is not a function

### ISSUE THREAD

**Issue by drunkendaddy** [nguymin4/react-videocall#10]
I'm able to call the other party. But accepting the call I'm getting this error:

`this.pc.setRemoteDescription is not function `

in app.js line 34;

I'm trying to get this to work on two browser windows on the same computer.

**Comment by nguymin4** [comment]
Hi, I cannot reproduce the bug. And you tried with 2 browser windows but same type (Chrome, Firefox) right?

**Comment by drunkendaddy** [comment]
I was testing by putting all your js files into my own project. I was loading your app.js component from another component in my project. So I had to remove
 
 `render(<VideoChat/>, document.getElementById('root'));`

from app.js to get it to working.

You may close this issue.
