### ISSUE TITLE
Not working on Mobile (Android / iOS) Chrome Browser

### ISSUE THREAD

**Issue by wajahatshaw** [nguymin4/react-videocall#11]
Not being able to work on Mobile Browser I have checked on Android (Chrome) 
This dialogue appears each time
![Screenshot_20190823-151544_Samsung Internet](https://user-images.githubusercontent.com/22732308/63639368-ad41f900-c6ab-11e9-93d0-c36353c7ee5d.jpg)

**Comment by Shaw08898** [comment]
/Users/eapple/Downloads/Screenshot_20190823-151544_Samsung Internet.jpg

**Comment by Shaw08898** [comment]
@nguymin4 Can you please resolve this issue?

**Comment by nguymin4** [comment]
Hi @Shaw08898, I can make call to my PC (Chromium, Linux) to my tablet (Android, Chrome).

**Comment by Shaw08898** [comment]
@nguymin4 I can also make a call, but my call does not get attended. Would you know the reason why? Like i press the answer button but nothing happens.

**Comment by nguymin4** [comment]
On Android, if I use Firefox Focus instead of normal Firefox, because the Mozilla disables some features which makes the call fails.

**Comment by nguymin4** [comment]
I'm using a Samsung Galaxy Tab A 10 (2016) as well - Android 8.1

**Comment by Shaw08898** [comment]
@nguymin4 , Are you using Chrome? 
I want to make calls from Android Tab to another Android Device / Tab

**Comment by nguymin4** [comment]
Yes, I'm using Chrome. Check my previous comment

> Hi @Shaw08898, I can make call to my PC (Linux, Chromium and Firefox) to my tablet (Android, Chrome).

**Comment by Shaw08898** [comment]
Can you please make a call to my Android Device? My ID is wandering-frog-8156

**Comment by nguymin4** [comment]
You can use https://test.webrtc.org/ to check if your browser supports it.

**Comment by Shaw08898** [comment]
Everything is supported except the Microphone! 
On Both Android Device and Chrome the same appeared. My Microphone is working well for other calls and stuff.
<img width="649" alt="Screen Shot 2019-08-24 at 8 43 23 PM" src="https://user-images.githubusercontent.com/22732308/63639684-ec724900-c6af-11e9-9759-938eda85657e.png">

**Comment by nguymin4** [comment]
Well at least we knew what is the problem.
