### ISSUE TITLE
Fix here to support iPhone devices

### ISSUE THREAD

**Issue by SergeiMeza** [nguymin4/react-videocall#14]
https://github.com/nguymin4/react-videocall/blob/ad232183c4b789aff51d8dcc0fbd9033d9d073b1/client/src/js/PeerConnection.js#L19

**Comment by SergeiMeza** [comment]
replace with ontrack

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/ontrack

**Comment by nguymin4** [comment]
Last time I tried to update there was problem, so please test it

https://github.com/nguymin4/react-videocall/commit/e4e24b9e15276321c15c4b1c163dac79fc18fbd1

**Comment by Vichp** [comment]
The online demo still doesn't work on iPhone - issue is that the stream is frozen on iOS safari. Any suggestions?

**Comment by nguymin4** [comment]
I haven't checked the latest iOS safari but as far as I know then iOS safari is not that friendly to WebRTC unfortunately.

**Comment by Vichp** [comment]
It's not the latest iOS safari, as I am using iOS 12.4.3. Did you push this bugfix into the production demo? @nguymin4

**Comment by nguymin4** [comment]
Yep it is in production.
