### ISSUE TITLE
Group Video call or video confrencing with multiple user

### ISSUE THREAD

**Issue by saddam1997** [nguymin4/react-videocall#17]
Hi,

Can any one help me i am trying to create group and make a video call with multiple user.

**Comment by nguymin4** [comment]
Hi, your request requires changing concept from person-person to person-room communication.
Although it's doable but cannot be quickly implemented. In the near future, I don't have any plan to support it.

**Comment by saddam1997** [comment]
Do you have any suggestions or any other example to implement "Group Video call" that I can follow?

**Comment by fivethreeo** [comment]
https://github.com/muaz-khan/RTCMultiConnection

**Comment by fivethreeo** [comment]
I really want to port that to es6 and decouple it form direct don manipulation so it works with react.

**Comment by nguymin4** [comment]
Yeah, the lib above is more well maintained and offers more features than mine. You can easily use that to create your own application.
