### ISSUE TITLE
9000 port not working from outside

### ISSUE THREAD

**Issue by somir** [nguymin4/react-videocall#18]
Hello,

How are you?
React-VideoCall is working fine from local PC but when I am deploying this application in remote server like AWS EC2, that time 9000 port not listening from outside. It's listening localhost only, server port 9000 port is open already. Can you please help me regarding this issue. 

> **tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      10777/node**

Thanks in Advance...
Somir

**Comment by nguymin4** [comment]
I think you need to configure inbound and outbound rules a bit
https://aws.amazon.com/premiumsupport/knowledge-center/connect-http-https-ec2/

**Comment by somir** [comment]
![Selection_060](https://user-images.githubusercontent.com/26133382/77518806-93b69900-6ea8-11ea-8c66-0ae5081bfdbe.png)

port already open, please find the screenshot.

**Comment by nguymin4** [comment]
Port 9000 is for webpack-dev-server. To deploy and run in production then you need to run `yarn build && yarn start` the server will listen at port 5000 by default unless you set it differently in `process.env.PORT`

**Comment by vishalkumarsinghvi** [comment]
amazing work @nguymin4  thanks a lot I used and everything is fine  in this  project

**Comment by nguymin4** [comment]
Thanks.

**Comment by vishalkumarsinghvi** [comment]
I create like tinder web app with the help of your video calling functionality . Have a look:- https://vikusi.netlify.app
