### ISSUE TITLE
no connection established after call has been picked up.

### ISSUE THREAD

**Issue by vaibhavpacharya** [nguymin4/react-videocall#2]
Hi,
Is there any network setting that needs to be done on local machine to establish a video call?

**Comment by nguymin4** [comment]
I guess you are testing the app locally. If in local machine, you use `chrome` and try to call to `firefox`, it will not work. Because the `camera`, as a resource, is occupied by `chrome`. However you can use different chrome tabs and try to call from one to another, it will work.
