### ISSUE TITLE
Call not connecting

### ISSUE THREAD

**Issue by Shibu-N** [nguymin4/react-videocall#3]
When I'm trying to run the same application in two different systems and trying to make a call it just goes to  the call window and the system I'm trying to connect is not showing any output. But when I'm trying to connect between two tabs inside a same browser its working good. Is there something I'm missing in here. Could you help me out?

**Comment by nguymin4** [comment]
Hi, I will check it during weekend and see if there is any problem.

**Comment by Shibu-N** [comment]
Thanks, let me know if there's any update.

**Comment by nguymin4** [comment]
Hi, I tested by calling from my computer to my phone, and everything is working. The only issue I noticed is that if the camera or mic of the device is malfunctioned then the app will not work. 

In general, the app should show notifications in case there are errors, ex: client id not found, camera/or mic doesn't work but unfortunately I don't have time to work on that feature.

**Comment by Shibu-N** [comment]
Thanks for helping me out. Can you tell me what server you are using on for the peer connection? Because If I'm running it on the browser on the localhost it's working fine. Only if I'm using it to connect between different systems there's no connectivity also no error is thrown. Is there something I'm missing. I just ran the code without any modifications to it. I'm totally stuck with it.

**Comment by nguymin4** [comment]
I used this one https://morning-escarpment-67980.herokuapp.com/

**Comment by Shibu-N** [comment]
The demo app works fine. But when cloning the same code and when trying to run it two different systems, I'm not able to establish an connection between the system.

**Comment by nguymin4** [comment]
Where do you deploy your app? I think heroku works just fine.
