### ISSUE TITLE
not work on ipad pro

### ISSUE THREAD

**Issue by meepeek** [nguymin4/react-videocall#4]
i try the demo with my android phone and ipad. android able to start the call, there was a popup in ipad to receive the call but touching both video and voice not work. however, red cancel button was working. i try calling from ipad but after enter the id and tap on call button, nothing happen

**Comment by nguymin4** [comment]
Sorry, I don't have ipad to test this out. My only guess is it has something to do with permissions to access mic and camera

**Comment by meepeek** [comment]
I have forgot to update. It was because the current iOS safari still not support WebRTC. Chrome and firefox on iOS also rely on safari so until it support, iOS devices are out.
