### ISSUE TITLE
<samp>

### ISSUE THREAD

**Issue by aalllliii** [nguymin4/react-videocall#55]
<samp>
Command 'rim' is not supported by Azure Pipelines.<br>
<br>
<b>Supported commands</b><br>
<ul type="none"><li><b>help:</b></li><ul type="none"><li>Get descriptions, examples and documentation about supported commands</li><li><b>Example: </b>help "command_name"</li></ul><li><b>list:</b></li><ul type="none"><li>List all pipelines for this repository using a comment.</li><li><b>Example: </b>"list"</li></ul><li><b>run:</b></li><ul type="none"><li>Run all pipelines or specific pipelines for this repository using a comment. Use this command by itself to trigger all related pipelines, or specify specific pipelines to run.</li><li><b>Example: </b>"run" or "run pipeline_name, pipeline_name, pipeline_name"</li></ul><li><b>where:</b></li><ul type="none"><li>Report back the Azure DevOps orgs that are related to this repository and org</li><li><b>Example: </b>"where"</li></ul></ul><br>
See <a href="https://go.microsoft.com/fwlink/?linkid=2056279">additional documentation.</a>
</samp>

__Originally posted by @azure-pipelines in https://github.com/dotnet/docfx/pull/8164#issuecomment-1235202438__

**Comment by nguymin4** [comment]
Please don't spam
