### ISSUE TITLE
is this still working 

### ISSUE THREAD

**Issue by BenGreybox** [nguymin4/react-videocall#9]
was wondering before starting to dig , the demo do not seem to work, is it a working project ?

**Comment by nguymin4** [comment]
It's deployed to free dyno on heroku so it will be put into sleep mode after being inactive for a certain amount of time and need a bit time to warm it up again. The background image is broken though. Otherwise the functionality is still working. 

I will not put any development effort on this app anymore. Probably fixing small issues is all I can do. Thanks.

**Comment by maaz28** [comment]
Hi Minh Son Nguyen, 
Thanks for the great project.
The application was working fine couple of weeks ago, but I couldn't be able to make a video call now
Would you please check whats wrong.

**Comment by nguymin4** [comment]
Hi maaz28,

What browser and OS are you using?

**Comment by maaz28** [comment]
It runs perfectly on chrome on my linux machine.

I couldn't be able to do a voice and video call from windows to linux
actually.

**Comment by nguymin4** [comment]
What happen if you open developer tool in Chrome on Windows and try to make the call.
Does it throw any error? If it throws `DOMException: Requested device not found` then I probably know what happened. I will quickly try to create more verbose error handling for that case.

**Comment by maaz28** [comment]
Therer is no error visible in console, Thanks for your time.

**Comment by nguymin4** [comment]
Ok now it becomes more interesting. I tested with Microsoft Edge, works ok. On Chrome, it throws the error above. But if doesn't throw any error then it's really weird.

**Comment by maaz28** [comment]
![Screenshot from 2019-06-21 15-59-47](https://user-images.githubusercontent.com/26284437/59918263-a0035680-943d-11e9-9cab-1be56c5276aa.png)

It just shows a blank window when I tried to do a videocall to another system.
It works fine on some machines.

**Comment by nguymin4** [comment]
Can you see the error log on the other machine? This current screenshot for current machine shows that everything works normally. So I guess, there's probably some problems on the other end.

**Comment by maaz28** [comment]
It doesn't show any error

**Comment by nguymin4** [comment]
What I can do now is I will deploy a branch which downgrade webrtc-adapter and let's see if it helps. Really hope that it solves your issue.

I deployed it now. Can you try it again? Thanks a lot.

**Comment by axe-z** [comment]
got it to work, only on chrome, hoped it would be commented , specially for the peerConnection file

**Comment by Sbphillips19** [comment]
No warnings for me either, just the blank screen.

**Comment by Sbphillips19** [comment]
Not sure what changed, but the heroku just started working

**Comment by lubhub612** [comment]
@nguymin4 I deployed it on my digital ocean , I shown this page 
![image](https://user-images.githubusercontent.com/45089340/75259122-8658b100-580d-11ea-96e0-d1d3b2b0dfed.png)
 I would like to know, how can I work in digital ocean

**Comment by nguymin4** [comment]
Port 5000 is the default I set.
You should check `process.env.PORT` to find out which port you use instead.
